/* Allegro datafile object indexes, produced by grabber v4.2.0, MinGW32 */
/* Datafile: c:\Users\apari\Desktop\final12\datosjuego.dat */
/* Date: Sat Nov 25 12:47:14 2017 */
/* Do not hand edit! */

#define dftextos                         0        /* FONT */
#define dibosque                         1        /* BMP  */
#define dibosquechoque                   2        /* BMP  */
#define dibosquesup                      3        /* BMP  */
#define dicasa                           4        /* BMP  */
#define dicasachoque                     5        /* BMP  */
#define dicasamago                       6        /* BMP  */
#define dicasasup                        7        /* BMP  */
#define dicity1                          8        /* BMP  */
#define dicity1choque                    9        /* BMP  */
#define dicity1sup                       10       /* BMP  */
#define dicursor                         11       /* BMP  */
#define diene001                         12       /* BMP  */
#define diene02                          13       /* BMP  */
#define diespada                         14       /* BMP  */
#define diinventario                     15       /* BMP  */
#define dilvlup                          16       /* BMP  */
#define dimago                           17       /* BMP  */
#define dimagochoque                     18       /* BMP  */
#define dimagosup                        19       /* BMP  */
#define dimenu                           20       /* BMP  */
#define dimenu1                          21       /* BMP  */
#define dimenu2                          22       /* BMP  */
#define dimenuchoque                     23       /* BMP  */
#define dimenusup                        24       /* BMP  */
#define dio001                           25       /* BMP  */
#define dio002                           26       /* BMP  */
#define dio003                           27       /* BMP  */
#define dio004                           28       /* BMP  */
#define dio005                           29       /* BMP  */
#define dio006                           30       /* BMP  */
#define diper001                         31       /* BMP  */
#define diper002                         32       /* BMP  */
#define diper003                         33       /* BMP  */
#define diper004                         34       /* BMP  */
#define diper005                         35       /* BMP  */
#define diper006                         36       /* BMP  */
#define diper007                         37       /* BMP  */
#define diper008                         38       /* BMP  */
#define dipersonaje                      39       /* BMP  */
#define dipersonaje0                     40       /* BMP  */
#define dipersonaje2                     41       /* BMP  */
#define ditienda1                        42       /* BMP  */
#define ditienda1choque                  43       /* BMP  */
#define ditienda1sup                     44       /* BMP  */
#define diwarrior                        45       /* BMP  */
#define dmcity1                          46       /* MIDI */
#define dmmenu                           47       /* MIDI */
#define dmmusica1                        48       /* MIDI */
#define dmmusica2                        49       /* MIDI */
#define dsaa                             50       /* SAMP */
#define dsabrirpuerta                    51       /* SAMP */
#define dsbosque                         52       /* SAMP */
#define dsboton1                         53       /* SAMP */
#define dsboton2                         54       /* SAMP */
#define dserror                          55       /* SAMP */
#define dsespada1                        56       /* SAMP */
#define dsespada2                        57       /* SAMP */
#define dsespada3                        58       /* SAMP */
#define dsmuerte01                       59       /* SAMP */
#define dspasos                          60       /* SAMP */
#define dsubenivel                       61       /* SAMP */

