/* Allegro datafile object indexes, produced by grabber v4.2.0, MinGW32 */
/* Datafile: c:\Users\apari\Desktop\FINAAAAAAL-master\datosjuego.dat */
/* Date: Wed Nov 29 01:08:40 2017 */
/* Do not hand edit! */

#define dftextos                         0        /* FONT */
#define dialcalde                        1        /* BMP  */
#define dianciano                        2        /* BMP  */
#define dibosque                         3        /* BMP  */
#define dibosquechoque                   4        /* BMP  */
#define dibosquesup                      5        /* BMP  */
#define dicasa                           6        /* BMP  */
#define dicasachoque                     7        /* BMP  */
#define dicasasup                        8        /* BMP  */
#define dicity1                          9        /* BMP  */
#define dicity1choque                    10       /* BMP  */
#define dicity1sup                       11       /* BMP  */
#define dicomerciante                    12       /* BMP  */
#define dicursor                         13       /* BMP  */
#define diecamino                        14       /* BMP  */
#define diecaminochoque                  15       /* BMP  */
#define diecaminosup                     16       /* BMP  */
#define diecastillo                      17       /* BMP  */
#define diecastillochoque                18       /* BMP  */
#define diecastillosup                   19       /* BMP  */
#define dieciudad                        20       /* BMP  */
#define dieciudadchoque                  21       /* BMP  */
#define dieciudadsup                     22       /* BMP  */
#define diecuarto                        23       /* BMP  */
#define diecuartochoque                  24       /* BMP  */
#define diecuartosup                     25       /* BMP  */
#define diegoal                          26       /* BMP  */
#define diegoalchoque                    27       /* BMP  */
#define diegoalsup                       28       /* BMP  */
#define dielfo                           29       /* BMP  */
#define diene001                         30       /* BMP  */
#define diepelired                       31       /* BMP  */
#define diespada                         32       /* BMP  */
#define digcampo                         33       /* BMP  */
#define digcampochoque                   34       /* BMP  */
#define digcamposup                      35       /* BMP  */
#define digcastillo                      36       /* BMP  */
#define digcastillochoque                37       /* BMP  */
#define digcastillosup                   38       /* BMP  */
#define digpueblo                        39       /* BMP  */
#define digpueblochoque                  40       /* BMP  */
#define digpueblosup                     41       /* BMP  */
#define digtorre                         42       /* BMP  */
#define digtorrechoque                   43       /* BMP  */
#define digtorresup                      44       /* BMP  */
#define diguardia                        45       /* BMP  */
#define diguerrero                       46       /* BMP  */
#define diinventario                     47       /* BMP  */
#define diladron                         48       /* BMP  */
#define dilvlup                          49       /* BMP  */
#define dimadre                          50       /* BMP  */
#define dimaestro                        51       /* BMP  */
#define dimago                           52       /* BMP  */
#define dimbosque                        53       /* BMP  */
#define dimbosquechoque                  54       /* BMP  */
#define dimbosquesup                     55       /* BMP  */
#define dimcastillo                      56       /* BMP  */
#define dimcastillochoque                57       /* BMP  */
#define dimcastillosup                   58       /* BMP  */
#define dimcuarto                        59       /* BMP  */
#define dimcuartochoque                  60       /* BMP  */
#define dimcuartosup                     61       /* BMP  */
#define dimenu                           62       /* BMP  */
#define dimenu2                          63       /* BMP  */
#define dimenut                          64       /* BMP  */
#define dimenutchoque                    65       /* BMP  */
#define dimenutsup                       66       /* BMP  */
#define dimoasis                         67       /* BMP  */
#define dimoasischoque                   68       /* BMP  */
#define dimoasissup                      69       /* BMP  */
#define dimpueblo1                       70       /* BMP  */
#define dimpueblo1choque                 71       /* BMP  */
#define dimpueblo2                       72       /* BMP  */
#define dimpueblo2choque                 73       /* BMP  */
#define dimpueblochoque                  74       /* BMP  */
#define dio001                           75       /* BMP  */
#define dio002                           76       /* BMP  */
#define dio003                           77       /* BMP  */
#define dio004                           78       /* BMP  */
#define dio005                           79       /* BMP  */
#define dio006                           80       /* BMP  */
#define diogro                           81       /* BMP  */
#define diper001                         82       /* BMP  */
#define diper002                         83       /* BMP  */
#define diper003                         84       /* BMP  */
#define diper004                         85       /* BMP  */
#define diper005                         86       /* BMP  */
#define diper006                         87       /* BMP  */
#define diper007                         88       /* BMP  */
#define diper008                         89       /* BMP  */
#define dipersonaje                      90       /* BMP  */
#define dipersonaje0                     91       /* BMP  */
#define dipersonaje2                     92       /* BMP  */
#define dipicaro                         93       /* BMP  */
#define dircasa                          94       /* BMP  */
#define dircasachoque                    95       /* BMP  */
#define dircasasup                       96       /* BMP  */
#define dircuarto                        97       /* BMP  */
#define dircuartochoque                  98       /* BMP  */
#define dircuartosup                     99       /* BMP  */
#define dirgoal                          100      /* BMP  */
#define dirgoalchoque                    101      /* BMP  */
#define dirgoalsup                       102      /* BMP  */
#define dirladrones                      103      /* BMP  */
#define dirladroneschoque                104      /* BMP  */
#define dirladronessup                   105      /* BMP  */
#define dirpueblo                        106      /* BMP  */
#define dirpueblochoque                  107      /* BMP  */
#define dirpueblosup                     108      /* BMP  */
#define ditienda1                        109      /* BMP  */
#define ditienda1choque                  110      /* BMP  */
#define ditienda1sup                     111      /* BMP  */
#define dmcity1                          112      /* MIDI */
#define dmmenu                           113      /* MIDI */
#define dmmusica1                        114      /* MIDI */
#define dmmusica2                        115      /* MIDI */
#define dsaa                             116      /* SAMP */
#define dsabrirpuerta                    117      /* SAMP */
#define dsbosque                         118      /* SAMP */
#define dsboton1                         119      /* SAMP */
#define dsboton2                         120      /* SAMP */
#define dserror                          121      /* SAMP */
#define dsespada1                        122      /* SAMP */
#define dsespada2                        123      /* SAMP */
#define dsespada3                        124      /* SAMP */
#define dsmuerte01                       125      /* SAMP */
#define dspasos                          126      /* SAMP */
#define dsubenivel                       127      /* SAMP */

